### ISSUE TITLE
Including ngFacebook dependency is breaking my controller

### ISSUE THREAD

**Issue by nathantechie9** [GoDisco/ngFacebook#39]
angular.module('<your-app>', ['ngFacebook'])

is causing

Argument 'FriendsCtrl' is not a function, got undefined

Is this plugin compatible with the following?

"dependencies": {
    "angular": "1.x",
    "angular-route": "1.x",
    "mobile-angular-ui": "1.2.x",
    "font-awesome": "4.x",
    "bootstrap": "3.x"

**Comment by joeltello** [comment]
I can't inject this module either. 
```
Error: [$injector:modulerr] Failed to instantiate module ClientApp due to:
[$injector:modulerr] Failed to instantiate module ngFacebook due to:
[$injector:nomod] Module 'ngFacebook' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.0-beta.16/$injector/nomod?p0=ngFacebook

```

**Comment by gbranco** [comment]
I'm getting the same, what was the solution for you @joeltello ?

**Comment by joeltello** [comment]
I don't remember what the issue was, but it was in my side, nothing to do with the library.

**Comment by angelxmoreno** [comment]
@gbranco do you have code?
