### ISSUE TITLE
Set accessToken instead of login.

### ISSUE THREAD

**Issue by sunshineo** [GoDisco/ngFacebook#40]
I know it sounds strange, but I actually have a valid use case for this.
I have the same code base for my website and my app. My app is a Cordova Phonegap app. I'm using angular to build it. However, on the phone, FB requires me to use the native experience. So I have to use this Cordova plugin for login: https://github.com/Wizcorp/phonegap-facebook-plugin

After login, I got the access token and everything. I want to use ngFacebook to call graph api, get data, etc. If I can set the access token onto $facebook and start using it, I can avoid writing 2 sets of code for web and phone separately.

Thank you very much!

**Comment by AlmogBaku** [comment]
Hey,
Actually, this module made for using with Cordova! so, it should support it natively.

The thing is- you can't set an `access_token` programaticlly with the fb-js-sdk, only after logging in with FB.
(but maybe you can use the Native java/obj. c to set it)

**Comment by AlmogBaku** [comment]
I closed this issue because it related mainly to the phonegap plugin, and there is nothing we can to about it here.

**Comment by sunshineo** [comment]
Thank you @AlmogBaku  I'll try to use this directly on Cordova and see if it brings out the native experience.
