### ISSUE TITLE
v1 is going to be deprecated soon

### ISSUE THREAD

**Issue by sunshineo** [GoDisco/ngFacebook#41]
End of April.
Can someone change to v2?

**Comment by wvanvlaenderen** [comment]
Can this be solved by the call '$facebookProvider.setVersion("v2.2");'?

**Comment by sunshineo** [comment]
The readme says
version(<string>) - specify the version of the api (v1.0 by default).

What I meant is to set the default to v2 instead of v1.0

**Comment by sunshineo** [comment]
Awesome!
