### ISSUE TITLE
Login in app build by Cordova / Ionic / Phonegap

### ISSUE THREAD

**Issue by danieleliberti** [GoDisco/ngFacebook#47]
After doing the build with Cordova / Ionic / Phonegap the app does not show the login window.

**Comment by AlmogBaku** [comment]
did you included the cordova facebook plugin?

**Comment by danieleliberti** [comment]
Yes
cordova plugin add https://github.com/phonegap/phonegap-facebook-plugin --variable APP_ID=your_facebook_app_id --variable APP_NAME=your_facebook_app_name

**Comment by AlmogBaku** [comment]
please try to check if you used the cordova plugin as well..  (you can try using weinre to debug, and to run on the console `FB.login()`.

In general, ngFacebook should work smoothly with cordova (as it was in my ex-startup).

**Comment by danieleliberti** [comment]
All configurations seem correct.
The build is created without errors .
Unfortunately, there is shown the window of the Facebook login .

Where can I download a small webapp testing for test.?

THX for the support

**Comment by AlmogBaku** [comment]
use the test directory from here with cordova+facebook.

**Comment by danieleliberti** [comment]
The problem was solved by changing the file for facebook sdk created and used by cordova.
 src="http://connect.facebook.net/en_US/sdk.js"

**Comment by AlmogBaku** [comment]
@danieleliberti you should not use the facebook sdk(that loaded from the url above).. you should you the cordova-facebook-sdk instead!
